### ISSUE TITLE
SUPEE-4829 not showing for Magento CE 1.9.1.0

### ISSUE THREAD

**Issue by bluec** [fballiano/magento-patches-finder#3]
Magento download page has SUPEE-4829 which it states is applicable only to Magento Community Edition 1.9.1

This script doesn't report SUPEE-4829 as being required for Magento CE 1.9.1.0

I'm not sure which is correct, but if the patch isn't required could the script include a comment about it?

**Comment by fballiano** [comment]
the notation on the official website for that patch it's really, really confusing, why the hell didn't they rename the "combobox element" instead of putting that invisibile note.

**Comment by bluec** [comment]
yeah it's really poor. I guess it's impossible for your scraper to account for their inconsistent approach so maybe just adding a note for any known inconsistencies like this one would be an option, or hard-coding this patch so that it shows as a result for 1.9.1.0?

**Comment by fballiano** [comment]
i can hardcode obviously, I don't know, at the end I think I'll have to do that anyway...

**Comment by fballiano** [comment]
so, that patch has only one download which says "EE 1.14" and a note saying "this patch is applicable only on 1.9.1" quite absurd.

I'll hardcode it for all 1.9.1.x releases also if it's completely not clear whatever they want to mean

**Comment by fballiano** [comment]
should be solved now, thanks for reporting!
