### ISSUE TITLE
SUPEE-3762 not showing for Magento CE 1.9.0.1

### ISSUE THREAD

**Issue by bluec** [fballiano/magento-patches-finder#4]
SUPEE-3762 applies to at least 1.9.0.1 but doesn't show in the results. I see the script attempts to match the version to the filename in the dropdown box but this script has an EE filename despite being required for CE.

**Comment by fballiano** [comment]
actually... the thing is that i wouldn't like to make a custom list of patches for magento versions... that patched is marked as EE, if it's not than it's a bug magento should solve...

dunno

**Comment by fballiano** [comment]
SUPEE-3762 it's been completely removed by magento's team:
http://magento.stackexchange.com/questions/80797/which-ee-and-ce-versions-need-the-supee-3762-patch-to-prevent-dos-attack

closing
