### ISSUE TITLE
laravel 5.2

### ISSUE THREAD

**Issue by Sejido** [fballiano/magento-patches-finder#5]
how can i integrate this code in my laravel 5.2 application 
thank you in advance

**Comment by fballiano** [comment]
it was not meant to be integrated in a laravel app, why would you do that?

**Comment by Sejido** [comment]
actually i need to detect missing patches in magento websites and i'm developing that using laravel , but when i found this code i think in integrate it to get the list of patches for the version that i pick

**Comment by fballiano** [comment]
it should be completely rewritten :)

**Comment by Sejido** [comment]
ok thank you anyway  :)

**Comment by Sejido** [comment]
can you tell me please how to rerwite this in order to use it in my application ?
